# Build stage
FROM node:lts AS builder

WORKDIR /app

# Copy source code and config files all at once
# We utilize .dockerignore to exclude node_modules
COPY webui .

# Install dependencies
RUN yarn install

# Build
RUN yarn run vite build --mode production

# Final stage
FROM nginx:stable-alpine

# Copy built assets
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
